import 'package:apex_store/model/shoe_model.dart';

List<ShoeModel> allShoes = [
  ShoeModel(
    shoeName: "Jordan 4",
    price: 249,
    rating: 5.0,
    brandName: "Nike",
    img: "assets/images/shoe4.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 3",
    price: 123,
    rating: 4.2,
    brandName: "Nike",
    img: "assets/images/shoe3.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 1",
    price: 243,
    rating: 4.5,
    brandName: "Nike",
    img: "assets/images/shoe1.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 2",
    price: 176,
    rating: 4.4,
    brandName: "Nike",
    img: "assets/images/shoe2.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),

  ShoeModel(
    shoeName: "Jordan 5",
    price: 199,
    rating: 4.7,
    brandName: "Nike",
    img: "assets/images/shoe5.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 6",
    price: 209,
    rating: 4.6,
    brandName: "Nike",
    img: "assets/images/shoe6.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 7",
    price: 165,
    rating: 4.3,
    brandName: "Nike",
    img: "assets/images/shoe7.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 8",
    price: 120,
    rating: 4.0,
    brandName: "Nike",
    img: "assets/images/shoe8.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 9",
    price: 234,
    rating: 4.9,
    brandName: "Nike",
    img: "assets/images/shoe9.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
  ShoeModel(
    shoeName: "Jordan 10",
    price: 241,
    rating: 4.7,
    brandName: "Nike",
    img: "assets/images/shoe10.png",
    description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
  ),
];
